name: 'code_quality'
variables:
  enable_all: 'true'
jobs:
  - job: 'UnitTests_Pester'
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 12
    strategy:
      parallel: 1
    pool:
      vmImage: 'win1803'
    steps:
    - powershell: Install-Module -Name Pester -Scope CurrentUser -Force -SkipPublisherCheck -AllowClobber
    - powershell:
        $pesterResult = Invoke-Pester -PassThru;
        if ($pesterResult.FailedCount) {
            echo "Pester unit tests have failed.";
            exit 1;
        } else {
            echo "Pester unit tests have passed.";
        }
  - job: 'PowerShellCodeCheck_PSScriptAnalyzer'
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 12
    strategy:
      parallel: 1
    pool:
      vmImage: 'win1803'
    steps:
    - powershell: Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force -SkipPublisherCheck -AllowClobber
    - powershell:
        $rules = @(
                 "PSUseDeclaredVarsMoreThanAssignments"
                );
        $errors = Invoke-ScriptAnalyzer -Path . -Recurse -IncludeRule $rules;
        if ($errors.Count -gt 0) {
            echo $errors;
            exit 1;
        } else {
            echo "PSScriptAnalyzer checks have passed."
        }
