# run name prefix to help grouping results, and put it in title.
name: best guest
# share configurations for similar runs.
parent: parentconfig.yaml
# it uses to support variables in other fields.
# duplicate items will be overwritten one by one.
# if a variable is not defined here, LISA can fail earlier to ask check it.
# file path is relative to LISA command starts.
variables:
  - path: secrets.yaml
    # If it's secret, it will be removed from log and other output information.
    # secret files also need to be removed after test is done.
    isSecret: true
  # continue to support v2 format. it's simple.
  - path: v2secrets.xml
    isSecret: true
  - path: env.yaml
  # redefine parameters in file to reuse configurations
  - name: username
    value: azureuser
    # it's not recommended highly to put secret in configurations directly.
    isSecret: true
# supports multiple artifacts in future.
artifacts:
  # name is optional. artifacts can be referred by name or index.
  - name: default
    type: vhd
    locations:
      http: https://path-to-azure-storage/aaa.vhd
  - name: dsvm
    type: vhd
    locations:
      http: https://path-to-azure-storage/bbb.vhd
# it's spec of environment and node.
# for ready type, it's optional
environment:
  topology: subnet
  template:
    - vcpu: 4
      # optional, if there is only one artifact
      artifact: default
      # sometimes, it may need special configuration for a platform
      # we should avoid this kind of setting, it limits configuration to other platforms.
      azure:
        - vmSize: testSize
  nodeCount: 
  nodes:
    - memoryGB: 4
      isDefault: true
    - memoryGB: 8
      gpuCount: 1
      artifact: dsvm
  # the environment spec may not be fully supported by each platform.
  # If so, there is a warning message.
  # Environment spec can be forced to apply, as error is loud.
  warnAsError: true
# it send test progress and results to any place wanted.
notifier:
  - type: junit
  - type: html
  - type: database
    connectionstring: $$ResultDatabaseString$$
# it's examples for all platforms, but currently should leave single one only.
platform:
  - name: default
    type: azure
    # it's platform specified parameters.
    subscription: $$SubscriptionID$$
    subscriptionKey: $$SubscriptionServicePrincipalKey$$
    datacenter: wu
    flag: "test=true"
  # for test case development, run test cases on current machine.
  - type: local
  - type: ready
    nodes:
      - ip: 10.0.0.1
        port: 22
        publicIp: 23.36.36.36
        publicPort: 1111
        # reference to environment variable
        password: $$linuxTestPassword$$
        privateKey: $$sshPrivateKey$$
        # If test suite doesn't specify where to run a case,
        #  it should be run on default node.
        isDefault: true
      - name: secondary
        ip: 10.0.0.2
        port: 22
        publicIp: 23.36.36.36
        publicPort: 1112
        password: $$linuxTestPassword$$
        privateKey: $$sshPrivateKey$$
# rules apply ordered on previous selection.
# The order of test cases running is not guaranteed, until it set dependencies.
tests:
  - criteria:
      # all rules in same criteria are AND condition.
      # we may support richer conditions later.
      # match case by name pattern
      name: "*-network*"
      # compatible with current test cases.
      area: network
      category: network
      priority: 0
      # tag is a simple way to include test cases within same topic.
      tag: vf
    # force to select. If any reason test cases are dropped, fail the run.
    forceInclude: true
    name: network
  # it means there are dependencies among test cases.
  - dependedOn: network
    # we will support some basic functionality of other test runner,
    # for example, environment information, once it's ready.
    # any other parameters should be handled by runner itself.
    type: LISAv2
    extraParameters: -TestNames "VERIFY-DEPLOYMENT-PROVISION" -ResourceCleanup Keep
  - name: settings
    criteria:
      name: this group shows different settings
    # run this group of test cases several times
    # default is 1
    iteration: 5
    # Once it's set, failed test result will be rewrite to success
    # it uses to work around some cases temporarily, don't overuse it.
    # default is false
    ignoreFailure: true
  - name: excluded cases
    criteria:
      name: "excluded test cases"
    # use to exclude some test cases
    # default is true
    include: false
  - name: unstable test cases
    criteria:
      name: "we don't have unstable case"
    # retry times. default is 0, means not retry.
    retry: 1
